# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Live deploy reports

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'

# permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Software dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Harvesting report
      run: |
        python scripts/gen_live_deploys_reports.py check
    - name: Validation report
      run: |
        python scripts/gen_live_deploys_reports.py validate
    - name: commit new data
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --local user.email "bioschemas-validation-bot@github.com"
          git config --local user.name "Bioschemas validation bot"
          git add .
          if git commit -m "Bioschemas Live Deploys harvesting and validation reports on $(date)"; then
              git push origin HEAD
              echo "successfully created new Bioschemas report"
          else
              echo "nothing new, exiting"            
          fi
